import { saveAs } from "file-saver";
// jsPDF and its autotable plugin are only needed when a user exports a PDF,
// so they're loaded on demand (dynamic import) to keep the initial bundle small.

export function exportToCSV(result) {
  const rows = [
    ["Factor", "Mother", "Father", "Total", "Min Range", "Max Range", "Higher Parent"],
    ...result.factors.map((f) => [
      f.label,
      f.mother.toFixed(3),
      f.father.toFixed(3),
      f.total.toFixed(3),
      f.min.toFixed(3),
      f.max.toFixed(3),
      f.higherParent,
    ]),
    [],
    ["Mother Total", result.motherTotal.toFixed(3)],
    ["Father Total", result.fatherTotal.toFixed(3)],
    ["Grand Total", result.grandTotal.toFixed(3)],
    ["Date of Birth", result.dob],
    ["Dominant Parent", result.dominantParent],
  ];

  const csvContent = rows.map((row) => row.map(csvEscape).join(",")).join("\r\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  saveAs(blob, `legacy-ledger-${result.dob}.csv`);
}

function csvEscape(value) {
  const str = String(value ?? "");
  if (str.includes(",") || str.includes('"') || str.includes("\n")) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export async function exportToPDF(result) {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Lineage Ledger", 14, 20);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Parental Legacy & Life Factors Report`, 14, 27);
  doc.text(`Date of Birth: ${result.dob}`, 14, 34);
  doc.text(`Dominant Parent: ${result.dominantParent.toUpperCase()}`, 14, 40);

  autoTable(doc, {
    startY: 47,
    head: [["Factor", "Mother", "Father", "Total", "Range"]],
    body: result.factors.map((f) => [
      f.label,
      f.mother.toFixed(3),
      f.father.toFixed(3),
      f.total.toFixed(3),
      `${f.min.toFixed(3)} - ${f.max.toFixed(3)}`,
    ]),
    foot: [
      ["Grand Total", result.motherTotal.toFixed(3), result.fatherTotal.toFixed(3), result.grandTotal.toFixed(3), ""],
    ],
    headStyles: { fillColor: [46, 110, 142] },
    footStyles: { fillColor: [182, 138, 46], textColor: 255 },
    styles: { fontSize: 9, cellPadding: 3 },
  });

  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(
    "Generated by Lineage Ledger. Values are illustrative, derived deterministically from the date of birth.",
    14,
    finalY
  );

  doc.save(`legacy-ledger-${result.dob}.pdf`);
}
